export const FETCH_COMPETITIONS_BEGIN = 'competitions/FETCH_COMPETITIONS_BEGIN';
export const FETCH_COMPETITIONS_SUCCESS =
  'competitions/FETCH_COMPETITIONS_SUCCESS';
export const FETCH_COMPETITIONS_FAILURE =
  'competitions/FETCH_COMPETITIONS_FAILURE';
