export const FETCH_MATCHES_BEGIN = 'matches/FETCH_MATCHES_BEGIN';
export const FETCH_MATCHES_SUCCESS = 'matches/FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAILURE = 'matches/FETCH_MATCHES_FAILURE';
